'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class SystemManagerObjects_Resources
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AutomateUI.SystemManagerObjects.Resources", GetType(SystemManagerObjects_Resources).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to You can only configure one Web API service at a time.
    '''</summary>
    Friend Shared ReadOnly Property ctlWebApiCanOnlyConfigureOneAtATime() As String
        Get
            Return ResourceManager.GetString("ctlWebApiCanOnlyConfigureOneAtATime", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Failed to add the Web API service to the database: {0}.
    '''</summary>
    Friend Shared ReadOnly Property ctlWebApiFailedToAddApiToDatabase() As String
        Get
            Return ResourceManager.GetString("ctlWebApiFailedToAddApiToDatabase", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Failed to remove Web API services: {0}.
    '''</summary>
    Friend Shared ReadOnly Property ctlWebApiFailedToRemoveWebApi() As String
        Get
            Return ResourceManager.GetString("ctlWebApiFailedToRemoveWebApi", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Failed to retrieve a list of Web API services from the database. Error message was &apos;{0}&apos;.
    '''</summary>
    Friend Shared ReadOnly Property ctlWebApiFailedToRetrieveList() As String
        Get
            Return ResourceManager.GetString("ctlWebApiFailedToRetrieveList", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Failed to update the Web API service&apos;s enabled state: {0}.
    '''</summary>
    Friend Shared ReadOnly Property ctlWebApiFailedToUpdateEnabledState() As String
        Get
            Return ResourceManager.GetString("ctlWebApiFailedToUpdateEnabledState", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Failed to update the Web API service: {0}.
    '''</summary>
    Friend Shared ReadOnly Property ctlWebApiFailedToUpdateWebApi() As String
        Get
            Return ResourceManager.GetString("ctlWebApiFailedToUpdateWebApi", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid action for the Web API service form: {0}.
    '''</summary>
    Friend Shared ReadOnly Property ctlWebApiInvalidActionForForm() As String
        Get
            Return ResourceManager.GetString("ctlWebApiInvalidActionForForm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Please select a single Web API service.
    '''</summary>
    Friend Shared ReadOnly Property ctlWebApiPleaseSelectASingleWebApi() As String
        Get
            Return ResourceManager.GetString("ctlWebApiPleaseSelectASingleWebApi", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Please first select one or more Web API services to delete.
    '''</summary>
    Friend Shared ReadOnly Property ctlWebApiPleaseSelectOneOrMoreToDelete() As String
        Get
            Return ResourceManager.GetString("ctlWebApiPleaseSelectOneOrMoreToDelete", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to This Web API is associated with the &apos;{0}&apos; Skill. Changing the Web API definition could stop the Skill from working. If required, reimport the Skill to overwrite any changes and revert the Web API definition to the default settings..
    '''</summary>
    Friend Shared ReadOnly Property ctlWebApiServices_WebApiIsLinkedToSkill() As String
        Get
            Return ResourceManager.GetString("ctlWebApiServices_WebApiIsLinkedToSkill", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Unexpected error &apos;{0}&apos;. Your new Web API service may not have been added successfully..
    '''</summary>
    Friend Shared ReadOnly Property ctlWebApiUnexpectedErrorAdded_Template() As String
        Get
            Return ResourceManager.GetString("ctlWebApiUnexpectedErrorAdded_Template", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to You must first select a Web API service to update.
    '''</summary>
    Friend Shared ReadOnly Property ctlWebApiYouMustSelectOneApiToUpdate() As String
        Get
            Return ResourceManager.GetString("ctlWebApiYouMustSelectOneApiToUpdate", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to You can only configure one web service at a time.
    '''</summary>
    Friend Shared ReadOnly Property ctlWebServicesViewCanOnlyConfigureOneAtATime() As String
        Get
            Return ResourceManager.GetString("ctlWebServicesViewCanOnlyConfigureOneAtATime", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Failed to update the Web service: {0}.
    '''</summary>
    Friend Shared ReadOnly Property ctlWebServicesViewFailedToUpdateWebService() As String
        Get
            Return ResourceManager.GetString("ctlWebServicesViewFailedToUpdateWebService", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The following services could not be deleted because they are associated with Skills:{0}.
    '''</summary>
    Friend Shared ReadOnly Property ctlWebServicesViewServicesCouldNotBeDeleted() As String
        Get
            Return ResourceManager.GetString("ctlWebServicesViewServicesCouldNotBeDeleted", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to You must first select at least one web service to update.
    '''</summary>
    Friend Shared ReadOnly Property ctlWebServicesViewYouMustSelectOneToUpdate() As String
        Get
            Return ResourceManager.GetString("ctlWebServicesViewYouMustSelectOneToUpdate", resourceCulture)
        End Get
    End Property
End Class
